name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

jobs:
  add-auto-response:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Auto Response to new issues
        uses: actions/github-script@v7
        with:
          script: |
            const message = `Thank you for raising this issue! Our team will review it soon. 
            For more queries, discussions, or approval of requests, please join our Discord server: [Discord Link](https://discord.com/invite/Yn9g6KuWyA)`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });